Urbetrack-Reservas/Models/ErrorViewModel.cs
using System;

namespace Urbetrack_Reservas.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Urbetrack-Reservas/Models/Reserva.cs
using System;

namespace UrbetrackReservas.Models
{
    public class Reserva
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Sala { get; set; }
        public DateTime Fecha { get; set; }
        public string TipoDeUso { get; set; }
        public int CantDePersonas { get; set; }

        public Reserva(Reserva reserva)
        {
            Id = reserva.Id;
            Nombre = reserva.Nombre;
            Sala = reserva.Sala;
            Fecha = reserva.Fecha;
            TipoDeUso = reserva.TipoDeUso;
            CantDePersonas = reserva.CantDePersonas;
        }

        public Reserva()
        {
        }
    }
}

Urbetrack-Reservas/Models/ReservaView.cs
using System.Collections.Generic;

namespace UrbetrackReservas.Models
{
    public class ReservaView
    {
        public List<Reserva> Reservas { get; set; }
        public List<Salon> Salones { get; set; }
        public ReservaView()
        {
        }

        public ReservaView(List<Reserva> reservas, List<Salon> salones)
        {
            Reservas = reservas;
            Salones = salones;
        }
    }
}

Urbetrack-Reservas/Models/Salon.cs
using System;
namespace UrbetrackReservas.Models
{
    public class Salon
    {
        public int Id { get; set; }
        public String Nombre { get; set; }
        public String Tipo { get; set; }
        public int Capacidad { get; set; }
        public Salon()
        {
        }

        public Salon(int id, string nombre, string tipo, int capacidad)
        {
            Id = id;
            Nombre = nombre;
            Tipo = tipo;
            Capacidad = capacidad;
        }
    }
}

Urbetrack-Reservas/Models/TipoSalon.cs
using System;

namespace UrbetrackReservas.Models
{
    public class TipoSalon
    {
        public int Id { get; set; }
        public String Nombre { get; set; }
        public int Capacidad { get; set; }
    }
}

Urbetrack-Reservas/Controllers/HomeController.cs
using System.Collections.Generic;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Urbetrack_Reservas.Models;

namespace Urbetrack_Reservas.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

Urbetrack-Reservas/Controllers/ReservasController.cs
using Microsoft.AspNetCore.Mvc;
using UrbetrackReservas.Models;
using UrbetrackReservas.Services;

namespace UrbetrackReservas.Controllers
{
    public class ReservasController : Controller
    {
        IReservasService _reservasService;

        public ReservasController(IReservasService reservasService)
        {
            _reservasService = reservasService;
        }
        public IActionResult Index()
        {
            ReservaView reservaView = _reservasService.GetIndexData();
            return View(reservaView);
        }
    }
}

Urbetrack-Reservas/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Urbetrack-Reservas/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<header>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
</header>
<div style="background-color:#fff; margin-top: 25%;height: 225px; display: flex; align-items: center;">
<h1 style="color:#5d3d85;margin-left: 30rem;">Realiza tus reservas</h1>
<button type="button" onclick="location.href='@Url.Action("", "Reservas")'"   class="btn btn-primary" style= "margin-top: 15px;background-color: #5d3d85; border-color: #5d3d85; margin-left: 20px; width: 120px;" >Reservar</button>
</div>

Urbetrack-Reservas/Views/Reservas/Index.cshtml
@model UrbetrackReservas.Models.ReservaView
<header>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <script>
        $(document).on('click', '#borrar', function (event) {
    event.preventDefault();
    $(this).closest('tr').remove();
    });
                $(document).on('keyup', '#nombre', function (event) {
        allowSave();
    });
                        $(document).on('change', '#fecha', function (event) {
        allowSave();
    });
                        $(document).on('change', '#cantidad', function (event) {
        allowSave();
    });

                $(document).on('click', '#agregar', function (event) {
          document.getElementById("tablaReservas").insertRow(1).innerHTML =
          '<td>'+$('#nombre').val()+'</td><td>'+$('#sala option:selected').text()+'</td><td>'+$('#fecha').val()+'</td><td>'+$('#tipoSalon option:selected').text()+'</td><td>'+$('#cantidad').val()+'</td><td><span class="table-edit"><button type="button" class="btn btn-warning btn-rounded btn-sm my-0" style="width:100%" data-toggle="modal" data-target="#myModal">Editar</button></span></td><td><span class="table-remove"><button type="button" id="borrar" class="btn btn-danger btn-rounded btn-sm my-0" style="width:100%">Cancelar Reserva</button></span></td>';
    });
        function allowSave() {
        nombre = $('#nombre').val();
        fecha = $('#fecha').val();
        cantidad= $('#cantidad').val();
        if(nombre !== '' && fecha !== '' && cantidad !== ''){
                $("#agregar").attr({"disabled" : false});
        }
        }

        function myFunction() {
        datamax = $('#tipoSalon option:selected').data("max");
        $("#cantidad").attr({"max" : datamax});
        }
                function myFunction2() {
        datamax2 = $('#tipoSalon2 option:selected').data("max");
        $("#cantidad2").attr({"max" : datamax2});
        }
    </script>
</header>
<div style="background-color:#fff; margin-top: 10%; display: flex; align-items: center; height: 500px;
    width: 100%; margin-left: 2%;">
    <form class="formulario" action="POST" style="margin-left: 2%; width:90%">
        <div>
            <h1 style="color:#5d3d85;">Reservas</h1>
            <p>Informacion importante: Tenga en cuenta que las reservas poseen reestricciones: No se aceptan reservas en feriados, el uso debe ser para un uso especifico y la cantidad de personas no debe superar el maximo permitido.</p>
            <table id="tablaReservas" class="table" style="width:100%">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Sala</th>
                        <th>Fecha</th>
                        <th>Tipo de Uso</th>
                        <th>Cantidad de Pers.</th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var reserva in Model.Reservas)
                    {
                        <tr>
                            <td>@reserva.Nombre</td>
                            <td>@reserva.Sala</td>
                            <td>@reserva.Fecha</td>
                            <td>@reserva.TipoDeUso</td>
                            <td>@reserva.CantDePersonas</td>
                            <td>
                                <span class="table-edit"><button type="button" class="btn btn-warning btn-rounded btn-sm my-0" style="width:100%" data-toggle="modal" data-target="#myModal">Editar</button></span>
                            </td>
                            <td>
                                <span class="table-remove"><button type="button" id="borrar" class="btn btn-danger btn-rounded btn-sm my-0" style="width:100%">Cancelar Reserva</button></span>
                            </td>
                        </tr>
                    }
                    <tr>
                        <td><input type="text" id="nombre" name="nombre" value="" class="form-control"></td>
                        <td>
                            <select id="sala" name="sala" class="form-control">
                                @foreach (var item in Model.Salones)
                                {
                                    <option value="@item.Id">
                                        @item.Nombre
                                    </option>
                                }
                            </select>
                        </td>
                        <td><input type="date" id="fecha" name="fecha" class="form-control"></td>
                        <td>
                            <select id="tipoSalon" name="tipoSalon" class="form-control" onchange="myFunction()">
                                @foreach (var item in Model.Salones)
                                {
                                    <option value="@item.Id" data-max="@item.Capacidad">
                                        @item.Tipo
                                    </option>
                                }
                            </select>
                        </td>
                        <td>
                            <input type="number" id="cantidad" name="cantidad" min="1" max="1" class="form-control">
                        </td>
                        <td></td>
                        <td>
                            <span class="table-add"><button type="button" id="agregar" disabled="true" class="btn btn-success btn-rounded btn-sm my-0" style="width:100%">Agregar</button></span>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </form>
    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Modifcar Reserva</h4>
                </div>
                <div class="modal-body">
                    <input type="text" id="nombre" name="nombre" value="" class="form-control">
                    <select name="sala" class="form-control">
                        @foreach (var item in Model.Salones)
                        {
                            <option value="@item.Id">
                                @item.Nombre
                            </option>
                        }
                    </select>
                    <input type="date" id="fecha-reserva" name="fecha-reserva" class="form-control">
                    <select id="tipoSalon2" name="tipoSalon2" class="form-control" onchange="myFunction2()">
                        @foreach (var item in Model.Salones)
                        {
                            <option value="@item.Id" data-max="@item.Capacidad">
                                @item.Tipo
                            </option>
                        }
                    </select>
                    <input type="number" id="cantidad2" name="cantidad2" min="1" max="1" class="form-control">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>

Urbetrack-Reservas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Urbetrack_Reservas</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div style="background-image:  url('images/BackgroundImage.jpg');     background-size: cover;
    background-repeat: no-repeat;     height: 766px;">
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <img src="~/images/logo.png" alt="Logo" />

                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-area="">Soluciones</a></li>
                        <li><a asp-area="">Plataforma</a></li>
                        <li><a asp-area="">Mercados</a></li>
                        <li><a asp-area="">Testimonios</a></li>
                        <li><a asp-area="">Nosotros</a></li>
                        <li><a asp-area="">Contacto</a></li>
                        <li><a asp-area="">Urbe Blog</a></li>
                        <li><a asp-area="">Acceso a Clientes</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        <partial name="_CookieConsentPartial" />

        <div class="container body-content">
            @RenderBody()
        </div>

        <environment include="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>
        <environment exclude="Development">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>

        @RenderSection("Scripts", required: false)
    </div>
</body>
</html>